### ISSUE TITLE
swap reporting_year and survey_acronym in censored data

### ISSUE THREAD

**Issue by randrescastaneda** [PIP-Technical-Team/pipapi#185]
Hey Guys, 

When I load the censored data after using the function `pipapi::create_versioned_lkups()` there is something that seems weird. As you can see in the image below, variables `reporting_year` and `survey_acronym` are swapped. 
![image](https://user-images.githubusercontent.com/35301997/150624615-8560b32c-69c2-4e3e-acab-17c346171477.png)

However, When I load the data directly from the output dir of the auxiliary data, variables `survey_acronym` and `reporting_year`  are correct. 
![image](https://user-images.githubusercontent.com/35301997/150624565-2bfd4e82-92de-4204-8192-7e942dc286b1.png)

I think this issue hast to be fixed as soon as possible, that's why I labelled it as "priority"

Best, 
Andres. 
@tonyfujs @Aeilert

**Comment by Aeilert** [comment]
Thanks @randrescastaneda 

This bug stemmed from a typo in the raw .xlsx file, but has previously been fixed. You probably see it in pipapi because the data repository you are using is out-of-sync with what we have on TFS. (After soft launch, let's see if we can set it up so that we all pull from the same repo). 

Closing this ticket, as it is not a code issue.
